### ISSUE TITLE
NameError: global name 'xs' is not defined

### ISSUE THREAD

**Issue by AlexJonsey** [ictnlp/OR-NMT#4]
bin/trainer.py: 
batch_beam_trgs = self.sampler.beam_search_trans(xs, xs_mask, ys_mask)

**Comment by zhang-wen** [comment]
sorry for the little bug,

**Comment by zhang-wen** [comment]
sorry for the bugs
xs, xs_mask and ys_mask are actually the input of the batch
the xs is returned by line 81
``_, xs, y_for_files, bows, x_lens, xs_mask, y_mask_for_files, bows_mask = batch``
please pass xs into the function beam_search_trans
