### ISSUE TITLE
training parameters

### ISSUE THREAD

**Issue by haorannlp** [ictnlp/OR-NMT#6]
Hi Zhang Wen,

Would you mind sharing the detailed training parameters that can reproduce the results for ``original transformer``,``oracle transformer in word level`` `` oracle transformer in sentence level ``in your paper?  It took me more than 10days to train a single base model. It is really hard for me to finetune the parameters on this huge dataset. Any help would be greatly appreciated.

**Comment by zhang-wen** [comment]
@haorannlp Hi, you could finetune based on the pretrained Transformer model for fast training. We will update the parameters.

**Comment by haorannlp** [comment]
@zhang-wen , could you share the way you implement scheduled sampling in Oracle transformer?

**Comment by zhang-wen** [comment]
@haorannlp please refer to our code for the details of the implementation.
