### ISSUE TITLE
epoch decay

### ISSUE THREAD

**Issue by haorannlp** [ictnlp/OR-NMT#7]
Hi Zhang Wen,

In your paper, you use ``epoch_decay`` to compute the sampling (gold) probability. Can I ask how many epochs did you run on the WMT dataset and what's the value of the best performing ``decay_k`` ? Thank you !

**Comment by zhang-wen** [comment]
@haorannlp Hi, Haoran, we have updated the experimental results and training details, please refer to https://github.com/ictnlp/OR-NMT.
